# Configuration file for Dirt-Limits

[general]
# Wether debug-messages should be printed to the console
debug = true
# Wether debug-messages should be colored in the console
coloredDebug = true
# How many list entries should be displayed before pagination is applied
listEntries = 10